<?php
/**
 * SPARE -- a special allocation group, kept separate from regular Blocks
 * (never "Block N", never auto-generated by Add Block). One SPARE group
 * exists per Program + Year Level, created on demand.
 *
 * GET    -> every SPARE group, each with its course allocations
 *           (allocation_type + target_block_id where applicable).
 * POST   ?action=ensure  { year_level, program_code? }
 *           -> gets-or-creates the SPARE group for that year level.
 * POST   ?action=allocate { spare_id, course_id, allocation_type, target_block_id? }
 *           -> sets (creates/updates) one course's SPARE allocation.
 *           allocation_type='join_block' requires target_block_id
 *           (must belong to the same year level, and must not already
 *           have a schedule plotted directly against the SPARE group for
 *           that course -- see below). allocation_type='separate_schedule'
 *           must NOT include target_block_id; this is the only case that
 *           later gets its own schedule row (schedules.spare_id).
 * DELETE ?spare_id=X&course_id=Y -> clears one course's SPARE allocation
 *           (blocked if a separate SPARE schedule already exists for it).
 */
require_once __DIR__ . '/bootstrap.php';
require_login();

function spare_with_allocations(PDO $pdo, int $spareId): array {
    $spareStmt = $pdo->prepare('SELECT * FROM spares WHERE id=?');
    $spareStmt->execute([$spareId]);
    $spare = $spareStmt->fetch();
    if (!$spare) return [];
    $allocStmt = $pdo->prepare(
        'SELECT sca.*, c.course_code, c.course_title, b.block_name AS target_block_name
         FROM spare_course_allocations sca
         JOIN courses c ON c.id = sca.course_id
         LEFT JOIN blocks b ON b.id = sca.target_block_id
         WHERE sca.spare_id = ?'
    );
    $allocStmt->execute([$spareId]);
    $spare['allocations'] = $allocStmt->fetchAll();
    return $spare;
}

try {
    $pdo = db();

    if ($_SERVER['REQUEST_METHOD'] === 'GET') {
        $spareIds = array_column($pdo->query('SELECT id FROM spares ORDER BY year_level')->fetchAll(), 'id');
        $result = array_map(fn($id) => spare_with_allocations($pdo, (int)$id), $spareIds);
        json_response(true, 'SPARE groups loaded', $result);
    }

    if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_GET['action'] ?? '') === 'ensure') {
        $d = input_json();
        require_fields($d, ['year_level']);
        $yearLevel = require_valid_year_level($d['year_level']);
        $programCode = $d['program_code'] ?? 'BSCS';

        $findStmt = $pdo->prepare('SELECT id FROM spares WHERE program_code=? AND year_level=?');
        $findStmt->execute([$programCode, $yearLevel]);
        $existingId = $findStmt->fetchColumn();
        if ($existingId) {
            json_response(true, 'SPARE group already exists', ['id' => (int)$existingId]);
        }
        $insertStmt = $pdo->prepare('INSERT INTO spares(program_code, year_level) VALUES(?,?)');
        $insertStmt->execute([$programCode, $yearLevel]);
        json_response(true, 'SPARE group created', ['id' => (int)$pdo->lastInsertId()], 201);
    }

    if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_GET['action'] ?? '') === 'allocate') {
        $d = input_json();
        require_fields($d, ['spare_id', 'course_id', 'allocation_type']);
        $spareId = (int)$d['spare_id'];
        $courseId = (int)$d['course_id'];
        $allocationType = $d['allocation_type'];
        if (!in_array($allocationType, ['join_block', 'separate_schedule'], true)) {
            json_response(false, 'allocation_type must be "join_block" or "separate_schedule".', null, 422);
        }

        $spareStmt = $pdo->prepare('SELECT * FROM spares WHERE id=?');
        $spareStmt->execute([$spareId]);
        $spare = $spareStmt->fetch();
        if (!$spare) json_response(false, 'SPARE group not found.', null, 404);

        $courseStmt = $pdo->prepare('SELECT * FROM courses WHERE id=?');
        $courseStmt->execute([$courseId]);
        $course = $courseStmt->fetch();
        if (!$course) json_response(false, 'Course not found.', null, 404);
        if ((int)$course['year_level'] !== (int)$spare['year_level']) {
            json_response(false, 'This course does not belong to the SPARE group\'s Year Level.', null, 422);
        }

        $targetBlockId = null;
        if ($allocationType === 'join_block') {
            if (empty($d['target_block_id'])) {
                json_response(false, 'target_block_id is required when allocation_type is "join_block".', null, 422);
            }
            $targetBlockId = (int)$d['target_block_id'];
            $blockStmt = $pdo->prepare('SELECT * FROM blocks WHERE id=?');
            $blockStmt->execute([$targetBlockId]);
            $block = $blockStmt->fetch();
            if (!$block) json_response(false, 'Target block not found.', null, 404);
            if ((int)$block['year_level'] !== (int)$spare['year_level']) {
                json_response(false, 'The target block must belong to the same Year Level as the SPARE group.', null, 422);
            }
        }

        // Guard: if this course already has a SPARE-separate schedule
        // plotted, it cannot be silently switched to "join_block" -- the
        // existing schedule would become orphaned/inconsistent. Delete the
        // schedule first, same pattern used for other structural edits.
        $currentStmt = $pdo->prepare('SELECT allocation_type FROM spare_course_allocations WHERE spare_id=? AND course_id=?');
        $currentStmt->execute([$spareId, $courseId]);
        $current = $currentStmt->fetch();
        if ($current && $current['allocation_type'] === 'separate_schedule' && $allocationType !== 'separate_schedule') {
            $scheduledStmt = $pdo->prepare('SELECT COUNT(*) FROM schedules WHERE spare_id=? AND course_id=?');
            $scheduledStmt->execute([$spareId, $courseId]);
            if ((int)$scheduledStmt->fetchColumn() > 0) {
                json_response(false, 'This course already has a separate SPARE schedule plotted. Delete it first before changing the allocation type.', null, 422);
            }
        }

        $stmt = $pdo->prepare(
            'INSERT INTO spare_course_allocations(spare_id, course_id, allocation_type, target_block_id)
             VALUES (?,?,?,?)
             ON DUPLICATE KEY UPDATE allocation_type=VALUES(allocation_type), target_block_id=VALUES(target_block_id)'
        );
        $stmt->execute([$spareId, $courseId, $allocationType, $targetBlockId]);
        json_response(true, 'SPARE allocation saved successfully');
    }

    if ($_SERVER['REQUEST_METHOD'] === 'DELETE') {
        $spareId = (int)($_GET['spare_id'] ?? 0);
        $courseId = (int)($_GET['course_id'] ?? 0);
        if (!$spareId || !$courseId) json_response(false, 'Missing spare_id or course_id', null, 422);

        $scheduledStmt = $pdo->prepare('SELECT COUNT(*) FROM schedules WHERE spare_id=? AND course_id=?');
        $scheduledStmt->execute([$spareId, $courseId]);
        if ((int)$scheduledStmt->fetchColumn() > 0) {
            json_response(false, 'This course already has a separate SPARE schedule plotted. Delete it first before removing the allocation.', null, 422);
        }

        $stmt = $pdo->prepare('DELETE FROM spare_course_allocations WHERE spare_id=? AND course_id=?');
        $stmt->execute([$spareId, $courseId]);
        if ($stmt->rowCount() === 0) json_response(false, 'Allocation not found.', null, 404);
        json_response(true, 'SPARE allocation removed');
    }

    json_response(false, 'Method not allowed', null, 405);
} catch (Throwable $e) { json_response(false, friendly_db_error($e), null, 500); }
